Feature/sass migrator
slavanga/baseguide pull request #17
Opened 2022-06-30 08:43 UTC by KasperAndersson

Closes https://github.com/slavanga/baseguide/issues/16

2022-07-02 17:22 UTC, slavanga commented
@KasperAndersson Hi Kasper, thank you for taking the time to submit this. I will review it 😊

2022-07-02 17:35 UTC, slavanga requested changes
@KasperAndersson looks very good overall. 

I left a few comments. Could you also add a new line after the last `@use` everywhere?

2022-07-02 17:35 UTC, slavanga commented on .nvmrc
> +14
@KasperAndersson Let's use 16.15.1 (latest LTS) here, then regenerate the lock files.

2022-07-02 17:35 UTC, slavanga commented on package.json
> +	},
Is this really needed? If yes please update to the LTS versions as well.
Also: should be indented using spaces.

2022-07-02 17:35 UTC, slavanga commented on package.json
> +		"sass": "^1.53.0",
Indent using spaces

2022-07-05 07:19 UTC, slavanga approved these changes

2022-07-05 07:20 UTC, merged

2022-07-05 07:20 UTC, slavanga commented
@KasperAndersson perfect 👌

2022-08-11 07:44 UTC, KasperAndersson commented
Hi @slavanga , do you plan to release this to npm registry?

2022-08-11 19:38 UTC, slavanga commented
Hey @KasperAndersson the changes are released now:
https://www.npmjs.com/package/baseguide/v/4.2.0